const state={token:localStorage.getItem('leave_token')||'',user:null,requests:[],page:'overview',selected:null};
const roleMeta={employee:{label:'Employee',tier:1,home:'employee',nav:[['overview','Overview','⌂'],['employee','Apply for leave','＋'],['requests','My requests','▣'],['audit','Audit trail','◌']]},hr:{label:'HR',tier:2,home:'hr',nav:[['overview','Overview','⌂'],['requests','HR review queue','☰'],['audit','Audit trail','◌']]},manager:{label:'Manager',tier:3,home:'manager',nav:[['overview','Overview','⌂'],['requests','Manager queue','☰'],['audit','Audit trail','◌']]},admin:{label:'Admin',tier:4,home:'admin',nav:[['overview','Overview','⌂'],['requests','Admin queue','☰'],['audit','Audit trail','◌']]},super_admin:{label:'Super Admin',tier:5,home:'super-admin',nav:[['overview','Overview','⌂'],['requests','Operations','☰'],['audit','Audit trail','◌']]}};
const roleLabel=r=>roleMeta[r]?.label||r;
const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function authHeaders(){return state.token?{Authorization:`Bearer ${state.token}`}:{}}
async function api(url,opt={}){const res=await fetch(url,{...opt,headers:{...(opt.headers||{}),...authHeaders()}});const text=await res.text();let body={};try{body=text?JSON.parse(text):{}}catch{body={detail:text}}if(!res.ok){if(res.status===401){logout(false)}throw new Error(body.detail||'Request failed')}return body}
function toast(msg,ok=false){const el=$('#toast');if(!el)return;el.textContent=msg;el.className=`toast ${ok?'ok':''}`;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2400)}
function statusLabel(s){return String(s||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}
function progressFor(status){return {PENDING_HR:25,PENDING_MANAGER:50,PENDING_ADMIN:75,APPROVED:100,REJECTED:100}[status]||0}
function timeline(status){const steps=[['Employee','Submitted'],['HR','Verified'],['Manager','Reviewed'],['Admin','Finalized'],['Super Admin','Notified']];const order={PENDING_HR:0,PENDING_MANAGER:1,PENDING_ADMIN:2,APPROVED:4,REJECTED:4};const idx=order[status]??0;return `<div class="timeline">${steps.map((s,i)=>{let cls=i<idx?'complete':i===idx?'current':'';if(status==='REJECTED'&&i===idx)cls='rejected';return `<div class="step ${cls}"><div class="dot">${i<idx?'✓':i+1}</div><span>${s[0]}<br>${s[1]}</span></div>`}).join('')}</div>`}
function requestCard(r,actions=''){return `<article class="request"><div><div class="request-title">Leave #${r.id} ${r.employee_id!=null?`· Employee #${r.employee_id}`:''}</div><div class="request-meta">${escapeHtml(r.start_date||'')} → ${escapeHtml(r.end_date||'')} · ${escapeHtml(r.reason||'')}</div></div><span class="status ${r.status}">${statusLabel(r.status)}</span><div class="queue-actions"><button class="btn soft" onclick="viewRequest(${r.id})">View</button>${actions}</div></article>`}
function shell(){document.body.innerHTML=`<div id="toast" class="toast hidden"></div><div class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">LF</div><div><strong>LeaveFlow</strong><span>Enterprise Leave</span></div></div><nav class="nav" id="nav"></nav><div class="side-bottom"><div class="user-card"><strong id="userName"></strong><span id="userRole"></span></div><button class="logout" id="logout">Sign out</button></div></aside><main class="main"><div class="topbar"><div class="title"><div class="eyebrow" id="tier"></div><h1 id="title"></h1><p id="subtitle"></p></div><div class="top-actions"><button class="btn" id="refresh">↻ Refresh</button></div></div><div id="content"></div></main></div><div id="modalRoot"></div>`;$('#logout').onclick=()=>logout(true);$('#refresh').onclick=loadRequests}
function buildNav(){const meta=roleMeta[state.user.role];$('#nav').innerHTML=meta.nav.map(n=>`<button class="${state.page===n[0]?'active':''}" onclick="navigate('${n[0]}')"><span class="icon">${n[2]}</span><span>${n[1]}</span></button>`).join('');$('#userName').textContent=state.user.username;$('#userRole').textContent=meta.label}
function headers(page){const meta=roleMeta[state.user.role];const map={overview:['Overview',`Your ${meta.label.toLowerCase()} workspace`],employee:['Apply for leave','Submit a request and follow every approval step'],requests:[meta.label==='Employee'?'My requests':`${meta.label} review queue`,'Focus on the requests that need your action'],audit:['Audit trail','Trace every decision and notification']};const h=map[page]||map.overview;$('#tier').textContent=`Tier ${meta.tier} · ${meta.label}`;$('#title').textContent=h[0];$('#subtitle').textContent=h[1]}
function navigate(page){state.page=page;buildNav();headers(page);render()}
function stats(){const all=state.requests;const counts={pending:all.filter(r=>r.status.startsWith('PENDING')).length,approved:all.filter(r=>r.status==='APPROVED').length,rejected:all.filter(r=>r.status==='REJECTED').length};return `<div class="grid stats"><div class="card stat"><div class="stat-label">Open workflow items</div><div class="stat-value">${counts.pending}</div><div class="stat-foot">Requests still moving through approval</div></div><div class="card stat"><div class="stat-label">Approved</div><div class="stat-value">${counts.approved}</div><div class="stat-foot">Final decisions granted</div></div><div class="card stat"><div class="stat-label">Rejected</div><div class="stat-value">${counts.rejected}</div><div class="stat-foot">Final decisions declined</div></div><div class="card stat"><div class="stat-label">Total requests</div><div class="stat-value">${all.length}</div><div class="stat-foot">Visible to your role</div></div></div>`}
function nextPanel(){const r=state.user.role;const target={employee:'PENDING_HR',hr:'PENDING_HR',manager:'PENDING_MANAGER',admin:'PENDING_ADMIN',super_admin:'APPROVED'}[r];const n=state.requests.find(x=>x.status===target);let title='You are all caught up';let body='There is nothing waiting for your action right now.';if(n){title=`Leave #${n.id} needs your attention`;body=`${r==='employee'?'Track the request as it moves through the approval flow.':'Open the request, review the details, and record your decision.'}`}return `<section class="card section"><div class="section-head"><div><div class="eyebrow">Next action</div><h2>${title}</h2><p>${body}</p></div></div>${n?`<div class="next-action"><div class="request-title">${escapeHtml(n.reason)}</div><div class="request-meta">${escapeHtml(n.start_date)} → ${escapeHtml(n.end_date)}</div><div style="margin-top:14px">${timeline(n.status)}</div><div class="progress-wrap"><div class="progress-row"><span>Approval progress</span><strong>${progressFor(n.status)}%</strong></div><div class="progress"><div style="width:${progressFor(n.status)}%"></div></div></div><div style="margin-top:16px"><button class="btn primary" onclick="viewRequest(${n.id})">Open request</button></div></div>`:''}</section>`}
function recentPanel(){return `<section class="card section"><div class="section-head"><div><div class="eyebrow">Activity</div><h2>Recent requests</h2></div><button class="btn" onclick="navigate('requests')">View all</button></div><div class="request-list">${state.requests.slice(0,4).map(r=>requestCard(r)).join('')||'<div class="empty">No leave requests yet.</div>'}</div></section>`}
function employeePage(){return `<div class="grid two"><section class="card section"><div class="section-head"><div><div class="eyebrow">New request</div><h2>Apply for leave</h2><p>Start your request here. It will enter HR review first.</p></div></div><form id="leaveForm" class="form-grid"><div class="field"><label>Start date</label><input name="start_date" type="date" required></div><div class="field"><label>End date</label><input name="end_date" type="date" required></div><div class="field wide"><label>Reason</label><textarea name="reason" minlength="5" maxlength="250" required placeholder="Briefly explain why you need leave"></textarea></div><div class="field wide"><label>Supporting document <span class="hint">optional · max 5 MB</span></label><input name="supporting_document" type="file" accept=".pdf,.png,.jpg,.jpeg,.doc,.docx"></div><div class="wide"><button class="btn primary" type="submit">Submit leave request</button></div></form><div id="leaveAlert"></div></section><section class="card section"><div class="eyebrow">How it works</div><h2>Your approval path</h2><p>Every request moves through the same five-tier sequence.</p>${timeline('PENDING_HR')}<div class="progress-wrap"><div class="progress-row"><span>Starts here</span><strong>25%</strong></div><div class="progress"><div style="width:25%"></div></div></div></section></div>`}
function queuePage(){const role=state.user.role;const filters=role==='employee'?state.requests:state.requests;const relevant=role==='employee'?filters:filters.filter(r=>r.status===({hr:'PENDING_HR',manager:'PENDING_MANAGER',admin:'PENDING_ADMIN',super_admin:null}[role]));return `<section class="card section"><div class="section-head"><div><div class="eyebrow">Queue</div><h2>${role==='employee'?'All my requests':relevant.length?`${relevant.length} request${relevant.length===1?'':'s'} waiting`:'No requests waiting'}</h2></div><div class="search-row"><input id="search" placeholder="Search by ID or reason"><select id="filter"><option value="all">All statuses</option><option value="PENDING_HR">Pending HR</option><option value="PENDING_MANAGER">Pending Manager</option><option value="PENDING_ADMIN">Pending Admin</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></div></div><div id="requestList" class="request-list"></div></section>`}
function auditPage(){return `<section class="card section"><div class="section-head"><div><div class="eyebrow">Traceability</div><h2>Audit trail</h2><p>Select a request to see every action taken.</p></div></div><div class="request-list">${state.requests.slice(0,12).map(r=>requestCard(r)).join('')||'<div class="empty">No requests available.</div>'}</div></section>`}
function render(){if(!state.user)return;headers(state.page);if(state.page==='overview'){$('#content').innerHTML=stats()+`<div class="grid two">${nextPanel()}${recentPanel()}</div>`;return}if(state.page==='employee'){$('#content').innerHTML=employeePage();$('#leaveForm').onsubmit=submitLeave;return}if(state.page==='requests'){$('#content').innerHTML=queuePage();renderRequestList();return}if(state.page==='audit'){$('#content').innerHTML=auditPage();return}}
function renderRequestList(){const box=$('#requestList');if(!box)return;const search=($('#search')?.value||'').toLowerCase();const filter=$('#filter')?.value||'all';let rows=state.requests.filter(r=>(filter==='all'||r.status===filter)&&(`${r.id} ${r.reason}`.toLowerCase().includes(search)));if(state.user.role!=='employee')rows=rows.filter(r=>r.status===({hr:'PENDING_HR',manager:'PENDING_MANAGER',admin:'PENDING_ADMIN',super_admin:null}[state.user.role])||state.user.role==='super_admin');box.innerHTML=rows.length?rows.map(r=>{let action='';if(state.user.role==='hr'&&r.status==='PENDING_HR')action=`<button class="btn primary" onclick="openReview(${r.id},'hr')">Review</button>`;if(state.user.role==='manager'&&r.status==='PENDING_MANAGER')action=`<button class="btn primary" onclick="openReview(${r.id},'manager')">Review</button>`;if(state.user.role==='admin'&&r.status==='PENDING_ADMIN')action=`<button class="btn primary" onclick="openReview(${r.id},'admin')">Finalize</button>`;if(state.user.role==='super_admin'&&['APPROVED','REJECTED'].includes(r.status))action=`<button class="btn primary" onclick="notifyEmployee(${r.id})">Notify</button>`;return requestCard(r,action)}).join(''):'<div class="empty">No matching requests.</div>';if($('#search')){$('#search').oninput=renderRequestList;$('#filter').onchange=renderRequestList}}
async function loadRequests(){try{state.requests=await api('/api/leave/requests');render()}catch(e){toast(e.message)}}
async function submitLeave(ev){ev.preventDefault();const form=ev.currentTarget;const fd=new FormData(form);try{const data=await api('/api/leave/submit',{method:'POST',body:fd});$('#leaveAlert').innerHTML='<div class="alert ok">Leave request submitted successfully.</div>';form.reset();await loadRequests();toast(`Leave #${data.id} created`,true)}catch(e){$('#leaveAlert').innerHTML=`<div class="alert error">${escapeHtml(e.message)}</div>`}}
function viewRequest(id){const r=state.requests.find(x=>x.id===id);if(!r)return;const documentHtml=r.document_name?`<div class="document"><strong>Supporting document</strong><div style="margin-top:6px">${escapeHtml(r.document_name)}</div><div style="margin-top:10px"><a href="/api/leave/${r.id}/document" target="_blank">Open document</a></div></div>`:'';$('#modalRoot').innerHTML=`<div class="modal-backdrop" onclick="closeModal(event)"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><div><div class="eyebrow">Leave request #${r.id}</div><h2 style="margin:4px 0 0">${escapeHtml(r.reason)}</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="detail" style="margin-top:18px"><dl class="kv"><dt>Employee</dt><dd>#${escapeHtml(r.employee_id)}</dd><dt>Start</dt><dd>${escapeHtml(r.start_date)}</dd><dt>End</dt><dd>${escapeHtml(r.end_date)}</dd><dt>Status</dt><dd><span class="status ${r.status}">${statusLabel(r.status)}</span></dd><dt>Created</dt><dd>${escapeHtml(r.created_at||'')}</dd></dl><div><div class="eyebrow">Approval timeline</div>${timeline(r.status)}<div class="progress-wrap"><div class="progress-row"><span>Progress</span><strong>${progressFor(r.status)}%</strong></div><div class="progress"><div style="width:${progressFor(r.status)}%"></div></div></div></div></div>${documentHtml}<div id="modalAudit" style="margin-top:18px"></div></div></div>`;loadAudit(id)}
async function loadAudit(id){try{const rows=await api(`/api/leave/${id}/audit`);const box=$('#modalAudit');if(!box)return;box.innerHTML=`<div class="eyebrow">Audit</div><div class="audit" style="margin-top:8px">${rows.map(a=>`<div class="audit-item"><strong>${escapeHtml(a.action_performed.replaceAll('_',' '))}</strong><div>${escapeHtml(a.comments||'')}</div><span>Actor #${escapeHtml(a.actor_id)} · ${escapeHtml(a.timestamp||'')}</span></div>`).join('')||'<div class="empty">No audit events yet.</div>'}</div>`}catch(e){}}
function closeModal(){ $('#modalRoot').innerHTML=''}
window.closeModal=closeModal;window.viewRequest=viewRequest;window.navigate=navigate;
function openReview(id,kind){const r=state.requests.find(x=>x.id===id);if(!r)return;$('#modalRoot').innerHTML=`<div class="modal-backdrop" onclick="closeModal(event)"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><div><div class="eyebrow">${kind==='admin'?'Final decision':'Review'} · Request #${id}</div><h2>${escapeHtml(r.reason)}</h2></div><button class="close" onclick="closeModal()">×</button></div><p style="color:var(--muted)">${escapeHtml(r.start_date)} → ${escapeHtml(r.end_date)} · Employee #${escapeHtml(r.employee_id)}</p><div class="field" style="margin-top:18px"><label>Decision comments</label><textarea id="reviewComments" maxlength="2000" placeholder="Add a clear decision reason"></textarea></div><div id="reviewAlert"></div><div style="display:flex;gap:10px;justify-content:flex-end;margin-top:16px"><button class="btn danger" onclick="submitReview(${id},'${kind}',false)">Reject</button><button class="btn primary" onclick="submitReview(${id},'${kind}',true)">Approve</button></div></div></div>`}
async function submitReview(id,kind,approved){const comments=$('#reviewComments').value.trim();if(!comments){$('#reviewAlert').innerHTML='<div class="alert error">Please enter comments before deciding.</div>';return}const endpoint={hr:`/api/leave/${id}/hr-review`,manager:`/api/leave/${id}/manager-approve`,admin:`/api/leave/${id}/admin-finalize`}[kind];try{await api(endpoint,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved,comments})});closeModal();await loadRequests();toast(approved?'Decision recorded':'Request rejected',true)}catch(e){$('#reviewAlert').innerHTML=`<div class="alert error">${escapeHtml(e.message)}</div>`}}
async function notifyEmployee(id){try{await api(`/api/leave/${id}/notify-employee`,{method:'POST'});await loadRequests();toast(`Employee notified for leave #${id}`,true)}catch(e){toast(e.message)}}
window.openReview=openReview;window.submitReview=submitReview;window.notifyEmployee=notifyEmployee;
async function bootstrap(){if(!state.token){location.href='/dashboard';return}try{state.user=await api('/api/auth/me');const pathPage={'/employee':'employee','/hr':'requests','/manager':'requests','/admin':'requests','/super-admin':'requests','/dashboard':'overview'}[location.pathname]||'overview';if(state.user.role==='employee'&&['/hr','/manager','/admin','/super-admin'].includes(location.pathname))location.href='/employee';if(state.user.role!=='employee'&&location.pathname==='/employee')location.href='/'+state.user.role.replace('_','-');state.page=pathPage;shell();buildNav();await loadRequests()}catch(e){logout(false)}}
function logout(go=true){state.token='';state.user=null;localStorage.removeItem('leave_token');if(go)location.href='/dashboard'}
document.addEventListener('DOMContentLoaded',bootstrap);
